name: Build and Deploy app

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
      name: 'Test'
      run: echo 'Test'
      
