name: Azure Bicep Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RG_NAME: test-deployment
  AZURE_LOCATION: westus3
  FOUNDATION_PARAMS: 
    - 'infra/parameters/acr.params.json'
    - 'infra/parameters/config.params.json'
    - 'infra/parameters/insights.params.json'
    - 'infra/parameters/kv.params.json'

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create RG
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.RG_NAME }} --location ${{ env.AZURE_LOCATION }}

      - name: Deploy Resources
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RG_NAME }}
          template: infra/templates/foundation.bicep
          parameters: ${{ join(env.FOUNDATION_PARAMS, ' ') }}
          failOnStdErr: false

      # - name: Deploy Website Resources
      #   uses: azure/arm-deploy@v1
      #   with:
      #     resourceGroupName: ${{ env.RG_NAME }}
      #     template: infra/templates/main.bicep
      #     parameters: infra/parameters/main.params.json
      #     failOnStdErr: false
